# Generated by Django 4.1.8 on 2023-05-16 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 5, 16, 11, 56, 37, 266311), editable=False),
        ),
    ]
