# Generated by Django 4.1.8 on 2023-05-16 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 11, 58, 34, 749371), editable=False),
        ),
    ]
