# Generated by Django 4.1.8 on 2023-05-18 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 9, 31, 6, 494211), editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'pdf'), ('docx', 'docx'), ('pptx', 'pptx'), ('rar', 'rar')], max_length=10, null=True),
        ),
    ]
