# Generated by Django 4.1.8 on 2023-05-18 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_author_created_at_alter_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 5, 18, 10, 27, 32, 64792), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
