# Generated by Django 4.1.8 on 2023-05-18 08:47

import app.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_author_created_at_alter_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 5, 18, 15, 47, 40, 612170), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_at',
            field=app.models.AutoDateTimeField(
                default=django.utils.timezone.now, editable=False),
        ),
    ]
