# Generated by Django 4.1.8 on 2023-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('XEM ĐƯỢC', 'XEM ĐƯỢC'), ('NHÁP', 'NHÁP')], default='NHÁP', max_length=100, null=True),
        ),
    ]
