# Generated by Django 4.1.8 on 2023-05-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deadline',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
    ]
