# Generated by Django 4.1.8 on 2023-05-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_department_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='image',
            new_name='image_dep',
        ),
    ]
