# Generated by Django 4.1.3 on 2023-03-29 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_result_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 14, 44, 2, 462222)),
        ),
    ]
