# Generated by Django 4.1.8 on 2023-05-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_image_department_image_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image_dep',
            field=models.ImageField(null=True, upload_to='department'),
        ),
    ]
