# Generated by Django 4.1.3 on 2023-03-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_name_lesson_headline_alter_author_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='headline',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 14, 54, 8, 775055)),
        ),
    ]
