# Generated by Django 4.0.10 on 2023-06-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_course_department_delete_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Department',
        ),
    ]
