# Generated by Django 4.1.3 on 2023-03-29 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_documents_alter_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 6, 26, 806786)),
        ),
    ]
