# Generated by Django 4.1.3 on 2023-03-29 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(default='Media/author/2021-11-19-14-04-25_0.png', upload_to='Media/author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 7, 31, 690699), editable=False),
        ),
    ]
