# Generated by Django 4.1.3 on 2023-03-29 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_author_created_at_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discount',
            new_name='sale',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 5, 0, 8759), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
