# Generated by Django 4.1.3 on 2023-03-29 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_discount_course_sale_alter_author_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sale',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 7, 30, 830457), editable=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
