# Generated by Django 4.1.3 on 2023-03-30 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_document_file_alter_author_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 14, 32, 43, 370822), editable=False),
        ),
    ]
