# Generated by Django 4.1.3 on 2023-03-30 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_author_slug_alter_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lessson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 15, 44, 13, 821337), editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
