# Generated by Django 4.1.3 on 2023-03-30 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_document_preview_alter_author_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='preview',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 16, 51, 25, 790945), editable=False),
        ),
    ]
