# Generated by Django 4.1.3 on 2023-04-04 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_document_preview_alter_author_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='lessson',
        ),
        migrations.AddField(
            model_name='document',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 14, 28, 51, 810384), editable=False),
        ),
    ]
