# Generated by Django 4.1.3 on 2023-04-04 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_document_lessson_document_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='lessson',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 14, 29, 49, 61845), editable=False),
        ),
    ]
