# Generated by Django 4.1.3 on 2023-04-04 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_document_preview_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 15, 5, 8, 214270), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(default='Media/author/gun_gru.jpg', null=True, upload_to='Media/featured_img'),
        ),
    ]
