# Generated by Django 4.1.3 on 2023-04-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_author_created_at_alter_course_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 15, 16, 47, 756716), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(default='Media/featured_img/gun_gru.jpg', null=True, upload_to='Media/featured_img'),
        ),
    ]
