# Generated by Django 4.1.3 on 2023-04-05 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_author_created_at_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 8, 33, 46, 635514), editable=False),
        ),
    ]
