# Generated by Django 4.1.3 on 2023-04-05 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(default='author/2021-11-19-14-04-25_0.png', upload_to='author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 10, 53, 7, 472321), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(default='featured_img/gun_gru.jpg', null=True, upload_to='featured_img'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='Documents'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Yt_Thumbnail'),
        ),
    ]
