# Generated by Django 4.1.3 on 2023-04-05 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_author_author_profile_alter_author_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 12, 31, 8, 987132), editable=False),
        ),
    ]
