# Generated by Django 4.1.3 on 2023-04-05 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_video_thumbnail_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 19, 44, 9, 739704), editable=False),
        ),
    ]
