# Generated by Django 4.1.3 on 2023-04-05 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_document_file_type_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 0, 13, 1, 226226), editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'pdf'), ('docx', 'docx'), ('pptx', 'pptx')], max_length=10, null=True),
        ),
    ]
