# Generated by Django 4.1.3 on 2023-04-06 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_author_created_at_alter_document_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 8, 51, 8, 892882), editable=False),
        ),
    ]
