# Generated by Django 4.1.3 on 2023-04-06 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_video_serial_number_alter_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='Yt_Thumbnail/youtube-thumbnails.jpg', null=True, upload_to='Yt_Thumbnail'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 8, 54, 1, 734678), editable=False),
        ),
    ]
