# Generated by Django 4.1.8 on 2023-04-10 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 13, 10, 38, 558545), editable=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.CharField(choices=[('python', 'fab fa-python'), ('java', 'fab fa-java')], max_length=200, null=True),
        ),
    ]
