# Generated by Django 4.1.8 on 2023-04-12 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_author_created_at_alter_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 17, 17, 8, 203809), editable=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.CharField(choices=[('fab fa-python', 'python'), ('fab fa-java', 'java'), ('fas fa-snowman', 'snowman')], max_length=200, null=True),
        ),
    ]
